default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: test_10_development

test:
  <<: *default
  database: test_10_test

production:
  <<: *default
  database: test_10_production